services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        sync: false
      - key: WEBHOOK_DOMAIN
        sync: false
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    preDeployCommand: python -c "import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)"
